---
title: "Aula para turma de calouros do Curso de Arquivologia da UFBA"
author: "Ricardo Sodré Andrade"
date: "2009-04-27"
categories: [arquivista-net]
description: "Relato de aula inaugural para calouros do curso de Arquivologia da UFBA."
draft: false
---

Na quinta-feira passada dei uma aula, a convite da Profa. Alzira, para a turma de calouros do novo curso noturno de Arquivologia da UFBA.
A orientação foi que eu deveria falar sobre o que eles poderiam esperar enquanto estudantes e profissionais. Qual o cenário estabelecido e minha visão sobre isso.
Iniciei falando da graduação e da experiência como bolsista de iniciação científica, algo que me permitiu ter sucesso na seleção de mestrado, logo após a colação de grau. Essa experiência, a participação no Diretório Acadêmico e as atividades de extensão fazem parte do ser universitário.
Também comentei sobre a dualidade existente na área, com a polarização das associações. Falei do Sindicato Nacional dos Arquivistas e dos eventos interessantes da área.
O mercado de trabalho também foi ponto explorado, considerando os concursos que tivemos nos últimos dois anos.
Me parece que eles ficaram animados, ou pelo menos estimulados com a situação da área no Brasil.
