---
title: "Disponibilização de bases de dados arquivísticas legadas na Web"
author: "Ricardo Sodré Andrade"
date: "2008-06-05"
categories: [arquivista-net]
description: "Artigo sobre a disponibilização de bases de dados arquivísticas legadas na Web."
draft: false
---

A maior parte das grandes instituições arquivísticas possuem suas bases de dados acerca dos acervos que custodiam. Geralmente são registros dos itens documentais, como é o caso do Arquivo Público da Bahia, cujas bases começaram a ser construídas a cerca de dez anos, salvo engano.
O grande problema dessas bases é que foram pensadas, construídas e mantidas ligadas a sistemas que permitem apenas a consulta local, sem acesso remoto. Disponibilizar essas bases na internet é um interessante desafio e muitas instituições ainda não conseguiram fôlego suficiente para encara-lo.
O Arquivo Público da Bahia tem um trabalho nesse sentido, intencionando a migração das suas bases para internet, o que demanda a mudança do Sistema Gerenciador de Banco de Dados e da interface utilizada. Atualmente estamos experimentando com o SGBD MySQL e a linguagem de programação PHP.
Qualificar os antigos e os novos instrumentos de referência/pesquisa por meio da adoção das normas de descrição arquivística é louvável, mas há muitos dados que podem ser úteis aos pesquisadores se estivessem disponibilizados, mesmo que não normalizados, na web.
Você conhece alguma instituição em situações ligadas a essa problemática? Já pensou sobre como ela está enfrentando a situação? Se desejar, mande um comentário contando!
