---
title: "Curso de ontologia em 8 horas"
author: "Ricardo Sodré Andrade"
date: "2009-04-06"
categories: [arquivista-net]
description: "Divulgação de curso intensivo de ontologia aplicada à representação da informação."
draft: false
---

No último final de semana fiz um curso sobre Ontologia. Chamava-se “Sistemas de Representação do Conhecimento: Ontologia” e foi organizado por uma ONG de Salvador que presta serviços na área de tecnologia.
Foram 8 horas no total. As primeiras quatro horas serviram para ter uma idéia do que seria o curso, em termos de conteúdo. As últimas quatro horas foram “facilitadas” por um instrutor diferente das quatro primeiras horas, ele era doutorando e  professor, isso facilitava o entendimento, pois ele organizava o pensamento e a fala.
Ontologia é uma forma de representar conceitos, definindo formalmente classes, entidades e relacionamentos dentro de um domínio. Lendo assim parece mais difícil do que talvez realmente seja.
Longe de tentar explicar o que é uma ontologia, sugiro uma passada na página do termo na Wikipédia. Talvez seja um bom ponto de partida.
As aulas práticas foram realizadas com o software livre Portégé, um editor de arquivos OWL, um formato baseado em XML, destinado a criar ontologias.
É tido que o OWL possibilita formalizar uma ontologia de forma “mais semântica” do que outros formatos, como o RDF. De fato, OWL é o formato indicado pela W3C, mas ainda não posso afirmar mais sobre ela.
Vou estudar isso e quem sabe tecer comentários mais úteis depois…
