---
title: "Formas de comunicação pessoal: a utilidade desse blog"
author: "Ricardo Sodré Andrade"
date: "2008-04-09"
categories: [arquivista-net]
description: "Reflexão sobre as formas de comunicação pessoal e a utilidade do blog como ferramenta."
draft: false
---

As pessoas fazem possuem blog pelos mais diversos motivos. Da criação de um diário pessoal e público, em um exercício egocêntrico, porém válido, até o que podemos chamar de utilidade pública, com a publicação de conteúdos úteis à outras pessoas.

Depois da criação do Portal do Arquivista, percebi que haviam coisas que eu queria falar, mas o portal não era o local. Notícias relacionadas às minhas idas aos eventos ou recentes publicações em periódicos destoavam dos conteúdos abrangentes que o portal costuma publicar.

Veio então a idéia de um blog pessoal, onde eu pudesse ter liberdade de publicar conteúdos que se referiam a mim e a meu trabalho. O nível de impessoalidade do Portal do Arquivista não irá vigorar aqui, é um espaço pessoal, porém, destinado a estabelecer comunicação com meus amigos e desconhecidos interessados em minha produção.

A utilidade se resume a ser um veículo do que eu fizer e que seja de interesse de outros, como o compartilhamento de pensamentos ou da produção de conhecimento que ocorre no âmbito do mestrado, minha atual atividade acadêmica ou do trabalho, ligado ao campo da Arquivologia.

E a comunicação não é unilateral, os campos de comentários existem para que seja possível a troca de impressões entre os visitantes, não deixe de comentar!
abraço,
Ricardo Sodré Andrade
