---
title: "Andanças por Goiânia: XV Congresso Brasileiro de Arquivologia"
author: "Ricardo Sodré Andrade"
date: "2008-07-05"
categories: [arquivista-net]
description: "Impressões do XV Congresso Brasileiro de Arquivologia em Goiânia."
draft: false
---

Acabou o XV Congresso Brasileiro de Arquivologia. Estive presente desde o segundo dia, por conta de um vôo de partida que não me esperou. Mas, pessoalmente, foi muito bom o congresso.
Minhas impressões pessoais foram muito boas, em parte por ter conhecido algumas figuras interessantes, como:
Peter Van Garderen, do projeto ICA-AtoM
Didier Grange, do Conselho Internacional de Arquivos
Jaime Antunes, Diretor do Arquivo Nacional
Leonardo Borges, da Femade
Antônio (não lembro o sobrenome!), do Arquivo da CUT
André Ancona Lopez, da UnB
Sérgio Albite
Tarcísio Barbosa, da UnB
Marília Neves, da equipe de apoio do evento
Jeane Silva, Arquivista da Petros
Além de outros que apresentaram comunicações durante o evento
Além de conhecer gente nova, ainda pude reencontrar algumas pessoas que eu já havia tido contato anteriormente, como:
Pedro Moura, do Arquivo Público de Pernambuco
Carlos Lima, do Arquivo Municipal de Paracatu – MG e que foi meu colega na UFBA
Angélica Marques, doutoranda da UnB
Muito bom esse contato com as pessoas que esses eventos proporcionam… Tenho diversas coisas pra registrar sobre o que aconteceu e sobre o que vi no congresso, mas vou ter que fazer isso em outra oportunidade…
E mal posso esperar pelo III Congresso Nacional de Arquivologia, no Rio de Janeiro!
