---
title: "Usando milhagens para ir aos eventos de Arquivologia"
author: "Ricardo Sodré Andrade"
date: "2008-04-22"
categories: [arquivista-net]
description: "Dicas sobre uso de programas de milhagem para participação em eventos da área."
draft: false
---

Recentemente descobri que um dos meus cartões de crédito possuía um programa de pontuação que permite a conversão em milhagens em companhias aéreas.

Me empolguei. Sai procurando os últimos tickets de passagens que eu possuía e comecei a transformá-los em pontos de milhagem, consegui 1800 pontos. O programa de milhagens que escolhi foi o da TAM, no qual eu já havia feito o cadastro, mas nunca havia transformado as passagens em pontos antes por falta de interesse.

A pontuação do cartão de crédito me rendeu mais 1800. Com esse somatório, já poderia economizar uma passagem de ida (a depender, eu voltaria andando…).

Descobri ainda que a TAM possui parceria com alguns cartões de credito, transformando cada real pago nas faturas em 1,33 pontos de milhagem. Isso iria aumentar em 33% o incremento da minha pontuação, disse eu cá com meus botões…
Se é pra pagar a fatura, que pelo menos eu ganhe milhagens… Esse ano teremos um punhado de eventos de Arquivologia e de Ciência da Informação que quero participar, portanto, as milhagens ajudam.

Fiz minha proposta para um desses cartões da TAM (pelo Itaúcard, pois o Unicard me complicou muito a vida…), se eles elevarem meu limite ao valor que quero, eu cancelo meus outros e uso apenas esse.
