---
title: "Primeiro dia de aula de um novo professor"
author: "Ricardo Sodré Andrade"
date: "2008-09-29"
categories: [arquivista-net]
description: "Registro do primeiro dia de aula como professor do curso de Arquivologia da UFBA."
draft: false
---

Na última quarta-feira dei aula para uma turma de graduação, como parte das atividades do mestrado. Era uma turma composta, em sua maioria, por estudantes de arquivologia e alguns de biblioteconomia. A disciplina: Metodologia da Pesquisa.
Achava que a quantidade de horas que tinha disponível era grande, teria que me esforçar para manter o ritmo durante todo aquele tempo, sem enrolar e sem deixar a aula inútil. Acho que consegui.
Questionei sobre qual a percepção que aquela disciplina provocava neles. Perguntei acerca do tema que tinham interesse para pesquisar. Levantei a possibilidade de que as possíveis dificuldades a serem encontradas iriam se concentrar no fato de que “o problema é justamente definir o problema de pesquisa”.
Eu apresentei da melhor forma possível as etapas necessárias para construção de um anteprojeto, falei sobre cada uma dessas etapas até os “objetivos específicos”.
Os questionamentos que foram levantados, as dúvidas explicitadas e o debate que por vezes se manifestava me fizeram ter a sensação de ter cumprido bem o papel de professor.
Foi um teste pessoal: poderia me tornar um bom professor?
O resultado me deixou com uma sensação de que poderia passar os próximos anos da vida fazendo isso também, se tiver oportunidade.
Vou lembrar de perguntar na próxima oportunidade o que acharam da aula. Simplesmente esqueci.
