---
title: "O Rio de Janeiro continua lindo: minhas impressões do III CNA e da cidade"
author: "Ricardo Sodré Andrade"
date: "2008-10-24"
categories: [arquivista-net]
description: "Impressões do III Congresso Nacional de Arquivologia e da cidade do Rio de Janeiro."
draft: false
---

Fui ao Rio de Janeiro quando tinha cerca de quatro anos. Boa parte das memórias que tenho daquele período só existem por conta das fotografias.

Confesso que evitava o Rio. A televisão, as notícias, a imprensa me mantinha afastado por conta de tudo, o “apesar dos pesares…” que antecede o “… a cidade ainda tem muito pra visitar”.

Não pude evitar, tive que faltar a algumas atividades do CNA para vistar o Amarelinho, a praça próxima a ele, o Arquivo Nacional…

Andar pelas ruas do Centro revelava os prédios monumentais. O teatro municipal em reforma continua imponente; a vista de cima do prédio da Funarte (cortesia do meu amigo Sílvio) foi providencial para quem não poderia olhar tudo de perto.

Filmei tudo quanto pude. A visita ao Arquivo Nacional, gentilmente acompanhado do Vitor Fonseca e da Silvia Moura; A assembléia de criação do Sindicato Nacional dos Arquivistas (boa parte não filmei direito, mas já estou em contato com outros colegas para troca de imagens). Enfim, imagem em movimento suficiente para vários vídeos no Youtube.

Tive a oportunidade de moderar uma mesa de comunicações nesse III CNA, além de apresentar uma comunicação relacionada à minha pesquisa no mestrado. Depois de publicar essa notícia, deverei colocar o texto completo na área de “Produção” desse site.
